### ISSUE TITLE
Consider updating vue/no-boolean-default rule

### ISSUE THREAD

**Issue by catrope** [wikimedia/jscs-preset-wikimedia#394]
Instead of disallowing a default value, force it to be false.

**Comment by Nightowl-8** [comment]
@catrope can you explain more about it?

**Comment by catrope** [comment]
Right now, if you define a Vue prop with a boolean type, we have a rule that prohibits you from setting a default value for the prop. The intent here is to prevent you from having boolean props that default to true (which is good), but we should do that by forcing the default to be false, rather than by forcing the default to be absent.

**Comment by Nightowl-8** [comment]
Hey @catrope , I searched out in this whole repo but i was not able to find any such instance. If you could tell me one?

**Comment by catrope** [comment]
Sorry for the late response; what I meant was that, in the default rules in `eslint-plugin-vue`, the `vue/no-boolean-default` rule prohibits setting a default value for boolean props at all. I'm saying we should override that, and instead allow `default: false` for boolean props. The rule has a mode to do that.
