### ISSUE TITLE
mediawiki/msg-doc should suppress length warnings

### ISSUE THREAD

**Issue by tgr** [wikimedia/jscs-preset-wikimedia#399]
`mediawiki/msg-doc` requires message keys to be enumerated in comments when a non-string argument is passed to `mw.msg()` or similar methods. Message keys tend to be long, and there is no possibility for line breaks in the comments. `max-len` warnings on the same line should be suppressed, if possible.

**Comment by edg2s** [comment]
The `max-len` lets you set regex patterns to ignore (https://eslint.org/docs/rules/max-len). Something like `^// * word-word-word$` could work.

The `msg-doc` rule itself is unable to talk to other rules, I believe.
