### ISSUE TITLE
Upgrade to  ESLint 8.x

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/jscs-preset-wikimedia#400]
We'll need to wait for amilajack/eslint-plugin-compat/issues/488 but beyond that it should be fine.

(Switching support to eslint 8.x means dropping node 10 support, so we can probably do that immediately for Wikimedia users but might want to tarry a little for other repos, and of course such a change would be a new major version.)

**Comment by edg2s** [comment]
Node 10 support dropped in #389.

**Comment by jdforrester** [comment]
> Node 10 support dropped in #389.

Oh right. In that case, let's JFDI?

**Comment by edg2s** [comment]
Still blocked by eslint-plugin-compat

**Comment by Tks4Fish** [comment]
eslint-plugin-compat seems to now support ESLint 8.x
