### ISSUE TITLE
Consider new rules from eslint-plugin-vue 7.20.0

### ISSUE THREAD

**Issue by edg2s** [wikimedia/jscs-preset-wikimedia#408]
https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.20.0

**Comment by catrope** [comment]
All the new rules in 7.20.0 look good and we should enable them, with the exception of `vue/no-deprecated-router-link-tag-prop`, which is for a Vue plugin that we don't use.

Thankfully, eslint-plugin-vue 8.0.0 (released earlier today) updates the presets, so we can remove all these manually reviewed rules from our config. I'll submit a PR to upgrade us straight to eslint-plugin-vue 8.0.2.
