### ISSUE TITLE
Allow functions to be used before they are defined

### ISSUE THREAD

**Issue by edg2s** [wikimedia/jscs-preset-wikimedia#434]
[`no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define) prevents functions from being used before they are defined, however this doesn't make much sense especially when you are using your functions like private methods. We have no equivalent rule for class methods (either in ES6 classes, or OOJS "classes").

See downstream proposal: https://gerrit.wikimedia.org/r/c/mediawiki/extensions/DiscussionTools/+/751821

We can leave this rule enabled for other variables, as it is important, especially as we allow multiple inline vars.

**Comment by edg2s** [comment]
cc @matmarex @krinkle

**Comment by Krinkle** [comment]
Sounds good to me. I'd recommend making sure that a violation through variables is covered by a test to avoid regressions, if not already coverered.
