### ISSUE TITLE
Release 0.23.0

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/jscs-preset-wikimedia#467]
- [x] #448
- [x] #450 
- [x] #453 
- [x] #455 
- [x] #456 
- [x] #457 
- [x] #458 
- [x] #459 
- [x] #460
- [x] #461
- [x] #463
- [x] #464 
- [x] #466  
- [x] #468 
- [x] #336
- [x] #470 
- [x] New eslint-plugin-mediawiki release
- -  [x] wikimedia/eslint-plugin-mediawiki/pull/78
- - [x] #469
- [ ] Others?

**Comment by edg2s** [comment]
#420 is about increasing test coverage so needn't block a release

**Comment by edg2s** [comment]
https://github.com/wikimedia/eslint-plugin-mediawiki/pull/80

**Comment by catrope** [comment]
Added #470, which would also be nice to get in

**Comment by catrope** [comment]
When do we plan to do this release?
