### ISSUE TITLE
Thoughts on "template-curly-spacing"

### ISSUE THREAD

**Issue by MatmaRex** [wikimedia/jscs-preset-wikimedia#509]
We're currently using `"template-curly-spacing": "error"`, which requires that there are no spaces within `${…}`, e.g.:

```javascript
`foo ${bar} baz`
```

This is good when the expression is just a variable. I wish, however, that we'd allow (or maybe even require) spaces when the expression within `${…}` is more complicated, e.g.:

```javascript
`<foo>${ mw.message( 'bar' ).parse() }</foo>`
```

I don't want to see *too* complicated expressions, though. We currently accept multi-line expressions within `${…}`. I wish that we'd reject them, e.g.:

```javascript
// INVALID ???
`<foo>${ mw.message(
    'bar',
    baz,
    super.log.call.something.something()
).parse() }</foo>`
```

```javascript
// INVALID ???
`foo ${
    mw.message( 'bar' ).text()
} baz`
```

ESLint doesn't seem to allow this kind of control. :(

**Comment by edg2s** [comment]
I agree we should enforce single spaces. At the time I went with existing conventions, but with spaces seems more consistent. The rule auto-fixes and is easily turned off.

**Comment by edg2s** [comment]
You could try filing the multi-line thing upstream.
