### ISSUE TITLE
Disallow inline else with curly braces

### ISSUE THREAD

**Issue by Daimona** [wikimedia/jscs-preset-wikimedia#511]
This issue is roughly the eslint equivalent of [T334993](https://phabricator.wikimedia.org/T334993) for PHPCS.

The [general coding conventions](https://www.mediawiki.org/wiki/Manual:Coding_conventions#Braceless_control_structures) give this example:

```php
// No:
if ( $done ) return;

// No:
if ( $done ) { return; }

// Yes:
if ( $done ) {
	return;
}
```

These are correctly enforced by the current configuration. However, the `max-statements-per-line` rule (which forbids inline ifs) does not handle `else` branches, meaning we get the following:

```js
if ( $done ) return 1; // Expected { after 'if' condition.(curly) -- good
else return 2; // Expected { after 'else'.(curly) -- good

if ( $done ) { return 2; } // This line has 2 statements. Maximum allowed is 1.(max-statements-per-line) -- good
else { return 3; } // No issue here!
```

In turn, that means the following snippet passes eslint:

```js
if ( $done ) {
	return 2;
} else { return 3; }
```

Instead, the `else` should be flagged because it's on a single line.

**Comment by jdforrester** [comment]
I would have thought this was something already in our upstream libraries, but a quick search didn't find anything. :-(

**Comment by edg2s** [comment]
The rule in question is `brace-style`

**Comment by Daimona** [comment]
> The rule we need to fix is `brace-style`

Oh, that's a useful pointer. Indeed, our config has:

```
"brace-style": [ "error", "1tbs", { "allowSingleLine": true } ],
```

where `allowSingleLine` is what makes eslint tolerate the bad example. This has been set to true since the initial commit, but I don't think it was intentional; or at least, it's not nowadays. I would guess that the other enabled rules provide enough coverage for the possible violations that nobody noticed this. `else` branches being the exception.

**Comment by edg2s** [comment]
It was intentional, to allow single line functions as object properties. The rule does not allow for functions to be treated differently to if/else blocks.

The `if` and `else if` cases are also covered by `max-statements-per-line`, but as an `else` itself contains no statement, this is not violated.

**Comment by edg2s** [comment]
> It was intentional, to allow single line functions as object properties. The rule does not allow for functions to be treated differently to if/else blocks.

That said `max-statements-per-line` means the single line functions only work in certain curcumstances:

Allowed:
```
var obj = {
  foo: function () { return 1; }
};
```
```
doThing(
  arg1,
  function () { return 1; }
);
```

Not allowed (multiple statements per line):
```
var x = function () { return 1; }
```
```
return function () { return 1; }
```

So getting rid of all single line functions might be a good idea.

**Comment by Daimona** [comment]
> It was intentional, to allow single line functions as object properties. The rule does not allow for functions to be treated differently to if/else blocks.

Ah, I didn't know that! In fact, it's not mentioned in the coding conventions.

> So getting rid of all single line functions might be a good idea.

Maybe? Also, for ES6 code this shouldn't be an issue as it could just use arrow functions.

**Comment by MatmaRex** [comment]
I'd also support `"allowSingleLine": false`. I think the only case where I'd really want the closing brace to be on the same line is for empty blocks, e.g.:

```
try {
  ...
} catch ( err ) {}
```

or

```
function () {}
```

…and that's still allowed even with `"allowSingleLine": false`.
