### ISSUE TITLE
Update to version 9.x of eslint-plugin-vue

### ISSUE THREAD

**Issue by catrope** [wikimedia/jscs-preset-wikimedia#514]
This is needed to support Vue 3.3.x, and also needed to avoid bugs when using ESLint >= 8.40.0. We encountered some bizarre behavior with ESLint 8.42.0 when setting up linting in IncidentReporting ([see Gerrit comments](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/IncidentReporting/+/928886/comment/47996901_72b8cbe9/)), and attempting to upgrade ESLint in Codex causes it to crash completely with a JS error from the `vue/no-unsupported-versions` rule.

As part of upgrading, we'll need to review the new rules introduced upstream and see if we want to enable them (and see if any of the ones that we've manually enabled have now become standard).

**Comment by jdforrester** [comment]
Ha, I did this as part of #513 (in attempts to fix security warnings that were blocking merges). Review appreciated!

**Comment by jdforrester** [comment]
Done.
