### ISSUE TITLE
Consider no-shadow:off for qunit preset

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/jscs-preset-wikimedia#532]
**Rationale**:

The idiomatic way to created nested QUnit scopes using modern ES6 syntax, involves shadowing the `hooks` variable, similar to how each test has its own `assert`, except this is lexical rather than linear, thus triggering this warning:

```
141:33  error  'hooks' is already declared in the upper scope on line 1 column 61  no-shadow
```

Upstream docs:
https://api.qunitjs.com/QUnit/module/#hooks-on-nested-modules

Example:
https://gerrit.wikimedia.org/r/c/mediawiki/core/+/970269/1/tests/qunit/resources/mediawiki.user.test.js

**Precedent**:
https://codesearch.wmcloud.org/deployed/?q=no-shadow&files=test&excludeFiles=&repos=

**Comment by edg2s** [comment]
You can also allow specific variable names: https://eslint.org/docs/latest/rules/no-shadow#allow
