### ISSUE TITLE
Release version with node 20 support

### ISSUE THREAD

**Issue by putnik** [wikimedia/jscs-preset-wikimedia#557]
The latest released version is still 0.26.0, which requires `eslint-plugin-jsdoc@^42.0.0`, and it doesn't allow to use it on node 20.
Could somebody publish a new release, please?

**Comment by edg2s** [comment]
Our CI runs against Node 16, 18 & 20 and is passing fine. What isn't working for you in Node 20?

**Comment by putnik** [comment]
```
% npm update
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@42.0.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```

**Comment by edg2s** [comment]
Those are just warnings, it should still install and run fine, like it does in our CI.

**Comment by jdforrester** [comment]
Now that v0.27.0 is out, this should be resolved. Please shout if you have any further issues!
