### ISSUE TITLE
jquery: emit warning or error for .done() and .fail()

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia/jscs-preset-wikimedia#564]
Using jQuery's .done() or .fail() instead of native JS promises .then() or catch():

1) contradicts the advice at https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Asynchronous_code

2) led to some nasty bugs in one repo I was working with, for example, [this patch](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/PageTriage/+/838851)

I'd suggest adding something like the below to our jQuery rules. Code below credit Kosta Harlan.

```json
"no-restricted-syntax": [
	"error",
	{
		"message": "Using .done() is not allowed. See https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Asynchronous_code",
		"selector": "MemberExpression > Identifier[name=\"done\"]"
	},
	{
		"message": "Using .fail() is not allowed. See https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Asynchronous_code",
		"selector": "MemberExpression > Identifier[name=\"fail\"]"
	}
],
```

**Comment by jdforrester** [comment]
Should this instead be a new https://github.com/wikimedia/eslint-plugin-no-jquery rule? @edg2s, thoughts?

**Comment by edg2s** [comment]
It would probably make sense to add the rules to the plugin, although they will be quite distinct from other rules, in that the apply to neither the `$` global object, or a `$collection`. That said "done" and "fail" are quite uncommon names for methods outside of promises.

**Comment by NovemLinguae** [comment]
I cut and pasted this ticket over to https://github.com/wikimedia/eslint-plugin-no-jquery/issues/332. Closing in this repo, leaving open in that repo.
