### ISSUE TITLE
Prefer arrow callbacks in ES6 code

### ISSUE THREAD

**Issue by edg2s** [wikimedia/jscs-preset-wikimedia#572]
We should consider the following rules in ES6 code:
* [prefer-arrow-callback](https://eslint.org/docs/latest/rules/prefer-arrow-callback)
* [arrow-body-style](https://eslint.org/docs/latest/rules/arrow-body-style)
* [implicit-arrow-linebreak](https://eslint.org/docs/latest/rules/implicit-arrow-linebreak)

This results in arrow functions being used for callbacks (unless they reference `this` or `arguments`, in which case they would need be converted manually). When arrow functions contain a single return statement, the body-less style is prefered (e.g. `( x ) => x + 1`. Also a single line is prefered for such body-less functions.

**Comment by jdforrester** [comment]
Seems sensible. Worth posting in https://www.mediawiki.org/wiki/Manual_talk:Coding_conventions/JavaScript for visibility?
